[pytest]

testpaths = Tests

python_files = test_*.py

python_classes = Test*

python_functions = test_*

markers =
    smoke: Smoke Test Cases
    sanity: Sanity Test Cases
    regression: Regression Test Cases

addopts =
    -v
    --html=Reports/report.html
    --self-contained-html